[package]
name = "sse_subscriber"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
reqwest-eventsource = "0.6.0"
log = "0.4.22"
env_logger = "0.11.5"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.16"
reqwest = "0.12.9"

